### PR TITLE
[RFR] Fix #24: bridge normalizer

### LINKED ISSUE #24: Error using fosrestbundle and jms serializer
Hi , 
I'm using your bundle together with fosrestbundle and jms Serializer, but im getting this error:

Type error: Argument 2 passed to CoopTilleuls\ForgotPasswordBundle\Controller\ForgotPasswordController::__construct() must be an instance of Symfony\Component\Serializer\Normalizer\NormalizerInterface, instance of JMS\Serializer\Serializer given

Another question is.. how can i customize de exceptions text of your bundle?

Regards

### PR DESCRIPTION
**Pull request by vincentchalamon**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24 
| License       | MIT

### CODE REVIEW

File: Bridge/Normalizer.php [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+namespace CoopTilleuls\ForgotPasswordBundle\Bridge;
+
+use JMS\Serializer\ArrayTransformerInterface;
+use JMS\Serializer\SerializerInterface as JMSSerializerInterface;
+use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
+
+/**
+ * @author Vincent Chalamon <vincent@les-tilleuls.coop>
+ */
+class Normalizer
```
Comment (meyerbaptiste) [inline Bridge/Normalizer.php]: Why not a `JmsNormalizerAdapter` class which implements the `NormalizerInterface` interface from Symfony? And in addition there will be no BC breaks in your `ForgotPasswordController` class.

**Comment by dunglas** [comment]
It does the trick but introducing an interface and an implementation by serializer would be more extensible (e.g. allow to use other/custom serializers).

File: Resources/config/services.xml [hunk 2]
```diff
@@ -5,9 +5,13 @@
         http://symfony.com/schema/dic/services/services-1.0.xsd">
 
     <services>
+        <service id="coop_tilleuls_forgot_password.normalizer" class="CoopTilleuls\ForgotPasswordBundle\Bridge\Normalizer">
```
Comment (dunglas) [inline Resources/config/services.xml]: Can be private

File: composer.json [hunk 3]
```diff
@@ -42,7 +42,8 @@
         "symfony/security-bundle": "^2.3 || ^3.0",
         "symfony/swiftmailer-bundle": "^2.3.11",
         "symfony/templating": "^2.3 || ^3.0",
-        "symfony/twig-bundle": "^2.8 || ^3.0"
+        "symfony/twig-bundle": "^2.8 || ^3.0",
+        "jms/serializer-bundle": "^1.4"
```
Comment (dunglas) [inline composer.json]: So the Symfony serializer should be moved to the `require-dev` section isn't it?

File: Bridge/Normalizer.php [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+{
+    /**
+     * @var NormalizerInterface|ArrayTransformerInterface
```
Comment (dunglas) [inline Bridge/Normalizer.php]: Useless docblock

File: Resources/config/services.xml [hunk 5]
```diff
@@ -5,9 +5,13 @@
...
+            <argument type="service" id="serializer" />
```
Comment (dunglas) [inline Resources/config/services.xml]: I would make this configurable (sometimes, you need to install both serializers in the same project).

File: Bridge/Normalizer.php (hunk 1 above)
Comment (dunglas) [inline Bridge/Normalizer.php]: It's too bad to depend of the `symfony/serializer` package just for an interface. Introducing a domain interface and creating adapter would be better.

File: DependencyInjection/Configuration.php [hunk 6]
```diff
@@ -72,6 +72,7 @@ public function getConfigTreeBuilder()
                         ->scalarNode('password_field')->defaultValue('password')->cannotBeEmpty()->info('User password field name.')->end()
                     ->end()
                 ->end()
+                ->booleanNode('use_jms_serializer')->defaultFalse()->end()
```
Comment (dunglas) [inline DependencyInjection/Configuration.php]: I suggest to let the user set a service name instead.

It will allow to deal with this config:

```yml
jms_serializer:    
    enable_short_alias: false
```

Comment (dunglas) [inline DependencyInjection/Configuration.php]: Let me explain it differently:

Define your normalizers using JMS's or Symfony's as private services. Let the user the the service name of the CoopTilleulsForgotPasswordBundle's to use.

It will allow the user to use other implementations of your interface.

File: DependencyInjection/CoopTilleulsForgotPasswordExtension.php [hunk 7]
```diff
@@ -47,5 +51,9 @@ public function load(array $configs, ContainerBuilder $container)
             throw new \LogicException(sprintf('Service "%s" does not exist.', $config['manager']));
         }
         $container->setAlias('coop_tilleuls_forgot_password.manager', $config['manager']);
+
+        // Build normalizer
+        $class = true === $config['use_jms_serializer'] ? JMSNormalizer::class : SymfonyNormalizer::class;
+        $container->setDefinition('coop_tilleuls_forgot_password.normalizer', new Definition($class, [new Reference('serializer')]))->setPublic(false);
```
Comment (dunglas) [inline DependencyInjection/CoopTilleulsForgotPasswordExtension.php]: You should use `jms_serializer` for JMS Serializer to prevent errors when the short alias is disabled.

File: DependencyInjection/Configuration.php (hunk 6 above)
Comment (vincentchalamon) [inline DependencyInjection/Configuration.php]: Something like:
```
coop_tilleuls_forgot_password:
    serializer: 'serializer' # Name of the serializer service to use
```

Am I correct?

Comment (vincentchalamon) [inline DependencyInjection/Configuration.php]: Cause I cannot declare both `JMSNormalizer` & `SymfonyNormalizer` as they require a service that may not exist, named differently, or implementing another class/interface. That's why I declare only one of them according to bundle configuration

File: DependencyInjection/CoopTilleulsForgotPasswordExtension.php (hunk 7 above)
Comment (vincentchalamon) [inline DependencyInjection/CoopTilleulsForgotPasswordExtension.php]: According to [this comment](https://github.com/coopTilleuls/CoopTilleulsForgotPasswordBundle/pull/25#discussion_r116262225), service `serializer` will be set by the user in the configuration (if I'm correct about your idea)

**Comment by vincentchalamon** [comment]
Ping @dunglas @meyerbaptiste
Can it be merged?

**Comment by dunglas** [comment]
let's go
